runtime:
  cache_dir: ./.cache/antora

site:
  title: Modern Application Development - Dev Track
  url: http://redhat-scholars.github.io/mad-dev-m1-guides/
  start_page: mad-dev-m1-guides::1-introduction.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: documentation

asciidoc:
  attributes:
    experimental: true
    openshift-password: openshift
    module-type: m1
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js

ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.12/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
